openapi: 3.0.2
info:
  version: 0.0.1
  title: '@viron/example-nodejs'
  description: api specifications
  x-viron-thumbnail: https://example.com/thumbnail.png
  x-viron-theme: standard
  x-viron-tags:
    - example

  x-viron-pages:
    - id: user
      title: ユーザー情報
      group: /Manage/Users/User
      contents:
        - getOperationId: listUser
          style: table
          primary: userId
          pagination: true
          query:
            - userId
            - email
          tableLabels:
            - userId
            - name
            - email
            - age
          sort:
            - userId
            - email
            - age
          autoRefreshSec: 10
          actions:
            - operationId: downloadCsv # GET: /csv_downloads/{module}/users/{userId}
              parameterMap:
                module: users 
                userId: {userId} 
          preview:
            method: get
            path: /users/{userId}/preview
            target: _blank
            parameterMap:
              userId: {userId}

servers:
  - url: /

tags:
  - name: user

paths:
  /users:
    get:
      operationId: listUser
      tags:
        - user
      summary: list user
      description: ユーザー情報
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    userId:
                      description: ユーザーID
                      type: string
                    name:
                      description: ユーザー名
                      type: string
                    email:
                      description: メールアドレス
                      type: string
                    age:
                      description: 年齢
                      type: number
      security:
        - jwt: []

components:
  securitySchemes:
    jwt:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://localhost:3000/signin
          scopes:
            api:access: API access

